# This pipeline will not run automatically; it must be triggered manually
trigger: none

pool:
  # Use the latest Ubuntu image for the build agent
  vmImage: 'ubuntu-latest'


variables:
  # Name of the Azure Container Registry (ACR)
  acrName: 'devopacr'
  # Azure DevOps service connection name
  azureSubscriptionServiceConnection: AzureConn
  # Path to the source code directory
  buildContextPath: 'src'
  # Use the build ID as the image tag
  tag: '$(Build.BuildId)'

stages:
- stage: CIStage
  displayName: CI stage

  jobs:
  - job: BuildAndPush
    displayName: Build & Push Image

    steps:
    - checkout: self
      displayName: 'Checkout source code'

    # Step: Login to Azure and Azure Container Registry (ACR)
    - task: AzureCLI@2
      displayName: Login to Azure and ACR
      inputs:
        azureSubscription: '$(azureSubscriptionServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into ACR..."
          az acr login --name $(acrName)

    # Step: Build and push Docker image for the backend service
    - task: Bash@3
      displayName: Build and push Docker image for backend
      inputs:
        targetType: 'inline'
        script: |
          echo "Building backend Docker image..."
          cd $(buildContextPath)
          docker build ./backend -t $(acrName).azurecr.io/backend:$(tag)
          docker tag $(acrName).azurecr.io/backend:$(tag) $(acrName).azurecr.io/backend:latest

          echo "Pushing backend Docker image to ACR..."
          docker push $(acrName).azurecr.io/backend:$(Build.BuildId)
          docker push $(acrName).azurecr.io/backend:latest

    #Step: Build and push Docker image for the frontend service
    - task: Bash@3
      displayName: Build and push Docker image for frontend
      inputs:
        targetType: 'inline'
        script: |
          echo "Building frontend Docker image..."
          cd $(buildContextPath)
          docker build ./frontend -t $(acrName).azurecr.io/frontend:$(tag)
          docker tag $(acrName).azurecr.io/frontend:$(tag) $(acrName).azurecr.io/frontend:latest

          echo "Pushing frontend Docker image to ACR..."
          docker push $(acrName).azurecr.io/frontend:$(Build.BuildId)
          docker push $(acrName).azurecr.io/frontend:latest
